package io.github.fontysvenlo.ais.persistence;

import io.github.fontysvenlo.ais.persistence.api.CustomerRepository;
import java.util.List;
import javax.sql.DataSource;

import io.github.fontysvenlo.ais.datarecords.CustomerData;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;

/**
 * This class knows everything about storing and retrieving customers from the database.
 * At the moment only returns dummy object with an id that is set.
 * Normally it will connect to a database and do all the handling.
 */
class CustomerRepositoryImpl implements CustomerRepository {
    
    private final DataSource db;
   // private final List<CustomerData> customers = new ArrayList<>(); 

    //without database delete after database
    private final List<CustomerData> customers = new ArrayList<>(Arrays.asList(new CustomerData(1, "John", "Doe", LocalDate.of(2025, 1, 1))         ,
    new CustomerData(2, "Jane", "Doe", LocalDate.of(2025, 1, 2)),
    new CustomerData(3, "Jim", "Beam", LocalDate.of(2025, 1, 3)),
    new CustomerData(4, "Jack", "Daniels", LocalDate.of(2025, 1, 4)),
    new CustomerData(5, "Johnny", "Walker", LocalDate.of(2025, 1, 5)))); 
    
    public CustomerRepositoryImpl(DBConfig config) {
        this.db = DBProvider.getDataSource(config);
    }

    /**
     * @see CustomerRepository#add(CustomerData)
     */
    @Override
    public CustomerData add(CustomerData customerData) {
        // Create dummy customerData object with id. Normally, the id would be generated by the database
        int maxId = customers.stream().mapToInt(CustomerData::id).max().orElse(0);
        CustomerData customerDataWithId = new CustomerData( ++maxId, customerData.firstName(), customerData.lastName(), customerData.dateOfBirth());
        customers.add(customerDataWithId);
        return customerDataWithId;
    }

    /**
     * @see CustomerRepository#getAll()
     */
    @Override
    public List<CustomerData> getAll() {
        // TODO: Implement the actual database storage
        // For now, return a dummy list
        return Collections.unmodifiableList(customers);
    }
}
